version: "3.8"

services:
  mail-dev:
    image: maildev/maildev
    restart: always
    ports:
      - "1025:1025"  # SMTP Port
      - "1080:1080"  # Web UI Port - you can see all email here :)
    volumes:
      - maildev-data:/root/.maildev  # Persist email data
  
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    platform: linux/amd64
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=appointment_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    volumes:
      - mysql_data:/var/lib/mysql
      - ./data/init.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-uuser", "-ppwd", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10


    

volumes:
  maildev-data:
  mysql_data: