name: CI Check for Deployment Verification

on:
  push:
    branches:
      - main  # This triggers the workflow whenever 'main' is modified (merged or direct commit)

jobs:
  verify-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make HTTP POST request to verify key
        run: |
          curl -X POST ${{ secrets.DEPLOYMENT_API_IP }} \
          -H "Content-Type: application/json" \
          -d '{"key": "${{ secrets.SECRET_KET_CD }}"}'
